### ISSUE TITLE
Missing IRequest 

### ISSUE THREAD

**Issue by rathakit** [omise/omise-node#134]
Getting the error when running `tsc` command - "node_modules/omise/types/index.d.ts(39,26): error TS2304: Cannot find name 'IRequest'."

`index.d.ts` - `updateAccount(req: IRequest, callback?: ResponseCallback<IAccount>): Bluebird<IAccount>;`

**Comment by rezigned** [comment]
Thank you for reporting. New version `0.8.2` already addressed this problem.
