### ISSUE TITLE
Refund missing argument

### ISSUE THREAD

**Issue by rathakit** [omise/omise-node#136]
Version 0.8.1
https://www.omise.co/refunds-api -> Create a refund
omise.charges.createRefund(
  'chrg_test_4ype2jynk2len88i4er',
  {'amount': 10000},
  function(error, refund) {
    /* Response. */
  }
);

From the example, it provides 3 arguments required; however, when calling this function, getting the error as following.
`Expected 1-2 arguments, but got 3.ts(2554)`

**Comment by rezigned** [comment]
Thank you for reporting. New version `0.8.2` already addressed this problem.
