### ISSUE TITLE
authorize_uri does not work. 

### ISSUE THREAD

**Issue by patricklee90** [omise/omise-node#197]
Dear Support,

I attempted to integrate Omise Internet Banking as a payment option, but I encountered an issue with the authorize_uri upon creating a charge. The error message displayed is as follows:

"Failed to launch 'krungsri-kma://map.payment?tokenId=7de8c5b6d2f44a36a196443d225c80f7' because the scheme does not have a registered handler."

To troubleshoot the problem, I performed the following validations:

[x] Verified the usage of Omise JS (2017 version).
[x] Confirmed successful creation of the charge request (see attached image: 
![image](https://github.com/omise/omise-node/assets/40401455/5e3ff6d6-cec2-41ba-a083-a907e2cdb1d1)
).
[x] Ensured that the backend was able to retrieve the Omise object response code, which displayed the following information:
{status: 'pending', status_code: 'redirect', authorize_uri: 'krungsri-kma://map.payment?tokenId=7de8c5b6d2f44a36a196443d225c80f7'}

Despite these validations, I encountered the aforementioned error when attempting to redirect the URL. I have tried both in a browser and a Flutter app's webview.
![image](https://github.com/omise/omise-node/assets/40401455/abcdfbe4-c9f1-4f81-80f8-5831ae85c159)

I kindly request your assistance and guidance in resolving this matter.

**Comment by patricklee90** [comment]
Updated. only KBank the deep link is working in flutter url_launcher package in webview (however kbank api return page not found)
![image](https://github.com/omise/omise-node/assets/40401455/e4a966f9-ec17-4068-8d2c-4f2b60c679d1)
![image](https://github.com/omise/omise-node/assets/40401455/0de4363a-547c-4a05-b8db-ced936e6b9f1)

The rest of the authorize_uri do not response which the link is not valid.
![image](https://github.com/omise/omise-node/assets/40401455/23e9592e-a6f8-45ed-990b-29b4d6b9619d)

**Comment by aashishgurung** [comment]
@patricklee90 Thanks for reaching out. It seems that you have implemented mobile banking instead of internet banking. Just to confirm, would you prefer to use internet banking or mobile banking?

**Comment by aashishgurung** [comment]
We’re going to close this since there hasn’t been any activity for a while. If this issue is still relevant, please feel free to reopen it with more details and we’ll take another look.
