### ISSUE TITLE
Interface ICharge did not return status attribute.

### ISSUE THREAD

**Issue by kal4506** [omise/omise-node#212]
### Expected behavior

return status attribute same as the document
https://docs.opn.ooo/charges-api

### Actual behavior

no status attribute in ICharge 

### Steps to reproduce the issue

Look at the types/index.d.ts file at line 225

### Name and version information

"omise": "0.12.0"

**Comment by aashishgurung** [comment]
@kal4506 Thank you for reaching out. We will work on it and let you know.

**Comment by aashishgurung** [comment]
@kal4506 The issue has been fixed in version `v0.12.1`. Thanks for your patience. We're closing this issue now.
