### ISSUE TITLE
capture flag ignored

### ISSUE THREAD

**Issue by lorenzofox3** [omise/omise-node#34]
Hi, when submitting the following request 
```Javascript
omise.charges.create({
    amount:5067,
    capture:false,
    card:"tokn_test_***",
    currency:"thb"
})
.then(function(result){
// ...
})
```

the result object says 
```Javascript
{
// ...  
    capture:true,
    captured:true,
// ...
}
```

however the http body passed [here](https://github.com/omise/omise-node/blob/master/lib/api.js#L79) seems correct, thus I suspect the error comes from the backend. 

How can I make sure my transaction has been authorized only ? (ie not captured)

Note: I am working with livemode=false and with test credit card 4111111111111111

regards, 

Laurent.R

**Comment by zdk** [comment]
It is because `JSON.stringify` I use here `https://github.com/omise/omise-node/blob/master/lib/api.js#L38` doesen't convert boolean into string 
so, atm, you may have to change to `capture: "false"` to just make it work.
sorry for your inconvenience.

**Comment by lorenzofox3** [comment]
great, thanks !

**Comment by zdk** [comment]
@lorenzofox3  Just for your information, we have also fixed the bug in our backend. So, if you'd like, you could use `capture:false` instead now ( which I think it's better ).

**Comment by lorenzofox3** [comment]
:+1: thanks !
