### ISSUE TITLE
Issue with WebPack

### ISSUE THREAD

**Issue by zacksiri** [omise/omise-node#60]
I'm trying to use the omise-node library with webpack to tokenize a card, this is what i'm getting

<img width="949" alt="screen shot 2560-01-18 at 9 14 19 pm" src="https://cloud.githubusercontent.com/assets/134488/22067299/52329b74-ddc3-11e6-8fa8-9afca19580d6.png">

**Comment by robinclart** [comment]
Hey @zacksiri we're looking at it. We'll report back once we find a fix.

**Comment by robinclart** [comment]
It seems this is related to this issue: https://github.com/webpack/webpack/issues/965

You need `json-loader` that you configure like so:

```
  preLoaders: [
        { test: /\.json$/, loader: 'json'},
    ],
```

Let me know if this fixes it.

**Comment by wingyplus** [comment]
@zacksiri Why you use webpack with omise-node library?
