### ISSUE TITLE
Error when import omise in React.js

### ISSUE THREAD

**Issue by tidjungs** [omise/omise-node#64]
try to import omise-node
```
const omise = require('omise')({
  'secretKey': 'skey_test_...',
  'omiseVersion': '2015-09-10'
});
```
<img width="649" alt="screen shot 2560-08-21 at 2 50 43 pm" src="https://user-images.githubusercontent.com/16177073/29508833-485f9e60-8680-11e7-9631-0b8f1ce3682e.png">

**Comment by tonmanna** [comment]
This repo used for nodejs app. You need to used omese js from this link https://www.omise.co/omise-js-api if you wish to add omese payment form client side.
