### ISSUE TITLE
Using the library for React Native

### ISSUE THREAD

**Issue by yishus** [omise/omise-node#83]
Working with a React Native app now, and previous suggestions have been to make use of this node library to create the token. 

Running into 2 issues
1. React Native can't do dynamic import but line 7 of `apiResources.js` has a require that is dynamic
2. `api.js` requires `bluebird` and `https` which the React Native library can't handle too

Wanted to check if there are possible solutions for integrating Omise into a React Native app other than writing our own native modules, or using a webview with `Omise.js`

**Comment by Antonhansel** [comment]
Hello @yishus 

This repository is for Node, have you checked this document ? https://www.omise.co/omise-js-api
It should help you implement omg on React Native

**Comment by ensecoz** [comment]
@yishus have you finally make omisejs working with react native.

@Antonhansel I search issue in omise-js and https://github.com/omise/omise.js/issues/11 it suggest to use omise-node and here it is suggest to use omise-js
